apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  annotations:
    camel.apache.org/operator.id: camel-k
    trait.camel.apache.org/service.type: NodePort
  name: push-policy-event
spec:
  sink:
    properties:
      region: eu-west-1
      stream: hdfc-policies
      accessKey: <redacted>
      secretKey: <redacted>
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: aws-kinesis-sink
  source:
    ref:
      apiVersion: camel.apache.org/v1
      kind: Kamelet
      name: webhook-source
  steps:
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: drop-headers-action
      properties:
        pattern: "*"
    - ref:
        kind: Kamelet
        apiVersion: camel.apache.org/v1
        name: avro-serial-action
      properties:
        url: http://example-apicurioregistry-mem-service:8080/apis/registry/v2/groups/hdfc/artifacts/policyCreateEvent/versions/1
